using Pitbull.Core.CQRS;
using Pitbull.Core.Domain;

namespace Pitbull.Billing.Features.JournalEntries;

public record JournalEntryDto(
    Guid Id,
    string EntryNumber,
    DateOnly EntryDate,
    string Description,
    JournalEntryStatus Status,
    string? SourceModule,
    Guid? SourceDocumentId,
    string? SourceDocumentRef,
    bool IsAutoGenerated,
    Guid? ReversalOfId,
    Guid? ReversedById,
    decimal TotalDebits,
    decimal TotalCredits,
    Guid? PostedByUserId,
    DateTime? PostedAt,
    IReadOnlyList<JournalEntryLineDto> Lines,
    DateTime CreatedAt,
    DateTime? UpdatedAt
);

public record JournalEntryLineDto(
    Guid Id,
    int LineNumber,
    Guid GlAccountId,
    string? AccountNumber,
    string? AccountName,
    decimal DebitAmount,
    decimal CreditAmount,
    string? Description,
    Guid? ProjectId,
    Guid? CostCodeId
);

public record CreateJournalEntryCommand(
    DateOnly EntryDate,
    string Description,
    string? SourceModule = null,
    Guid? SourceDocumentId = null,
    string? SourceDocumentRef = null,
    bool IsAutoGenerated = false,
    List<CreateJournalEntryLineCommand>? Lines = null
) : ICommand<JournalEntryDto>;

public record CreateJournalEntryLineCommand(
    Guid GlAccountId,
    decimal DebitAmount,
    decimal CreditAmount,
    string? Description = null,
    Guid? ProjectId = null,
    Guid? CostCodeId = null
);

public record UpdateJournalEntryCommand(
    Guid JournalEntryId,
    DateOnly? EntryDate = null,
    string? Description = null,
    List<CreateJournalEntryLineCommand>? Lines = null
) : ICommand<JournalEntryDto>;

public record ListJournalEntriesQuery(
    JournalEntryStatus? Status = null,
    DateOnly? StartDate = null,
    DateOnly? EndDate = null,
    string? SourceModule = null,
    string? Search = null,
    int Page = 1,
    int PageSize = 25
) : IQuery<ListJournalEntriesResult>;

public record ListJournalEntriesResult(
    IReadOnlyList<JournalEntryDto> Items,
    int TotalCount,
    int Page,
    int PageSize,
    int TotalPages
);
