using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Pitbull.Billing.Features.JournalEntries;
using Pitbull.Billing.Services;
using Pitbull.Core.Domain;

namespace Pitbull.Api.Controllers;

[ApiController]
[Route("api/journal-entries")]
[Authorize(Roles = "Admin")]
[EnableRateLimiting("api")]
[Produces("application/json")]
[Tags("Journal Entries")]
public class JournalEntriesController(IJournalEntryService journalEntryService) : ControllerBase
{
    [HttpGet]
    [ProducesResponseType(typeof(ListJournalEntriesResult), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    public async Task<IActionResult> List(
        [FromQuery] JournalEntryStatus? status,
        [FromQuery] DateOnly? startDate,
        [FromQuery] DateOnly? endDate,
        [FromQuery] string? sourceModule,
        [FromQuery] string? search,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 25)
    {
        ListJournalEntriesQuery query = new(status, startDate, endDate, sourceModule, search, page, pageSize);
        var result = await journalEntryService.GetJournalEntriesAsync(query);

        if (!result.IsSuccess)
            return BadRequest(new { error = result.Error, code = result.ErrorCode });

        return Ok(result.Value);
    }

    [HttpGet("{id:guid}")]
    [ProducesResponseType(typeof(JournalEntryDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    public async Task<IActionResult> GetById(Guid id)
    {
        var result = await journalEntryService.GetJournalEntryAsync(id);
        if (!result.IsSuccess)
            return result.ErrorCode == "NOT_FOUND"
                ? NotFound(new { error = result.Error, code = result.ErrorCode })
                : BadRequest(new { error = result.Error, code = result.ErrorCode });

        return Ok(result.Value);
    }

    [HttpPost]
    [ProducesResponseType(typeof(JournalEntryDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    public async Task<IActionResult> Create([FromBody] CreateJournalEntryRequest request)
    {
        CreateJournalEntryCommand command = new(
            EntryDate: request.EntryDate,
            Description: request.Description,
            SourceModule: request.SourceModule,
            SourceDocumentId: request.SourceDocumentId,
            SourceDocumentRef: request.SourceDocumentRef,
            IsAutoGenerated: request.IsAutoGenerated,
            Lines: request.Lines?.Select(l => new CreateJournalEntryLineCommand(
                GlAccountId: l.GlAccountId,
                DebitAmount: l.DebitAmount,
                CreditAmount: l.CreditAmount,
                Description: l.Description,
                ProjectId: l.ProjectId,
                CostCodeId: l.CostCodeId
            )).ToList()
        );

        var result = await journalEntryService.CreateJournalEntryAsync(command);
        if (!result.IsSuccess)
            return BadRequest(new { error = result.Error, code = result.ErrorCode });

        return CreatedAtAction(nameof(GetById), new { id = result.Value!.Id }, result.Value);
    }

    [HttpPut("{id:guid}")]
    [ProducesResponseType(typeof(JournalEntryDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    public async Task<IActionResult> Update(Guid id, [FromBody] UpdateJournalEntryRequest request)
    {
        UpdateJournalEntryCommand command = new(
            JournalEntryId: id,
            EntryDate: request.EntryDate,
            Description: request.Description,
            Lines: request.Lines?.Select(l => new CreateJournalEntryLineCommand(
                GlAccountId: l.GlAccountId,
                DebitAmount: l.DebitAmount,
                CreditAmount: l.CreditAmount,
                Description: l.Description,
                ProjectId: l.ProjectId,
                CostCodeId: l.CostCodeId
            )).ToList()
        );

        var result = await journalEntryService.UpdateJournalEntryAsync(command);
        if (!result.IsSuccess)
        {
            return result.ErrorCode switch
            {
                "NOT_FOUND" => NotFound(new { error = result.Error, code = result.ErrorCode }),
                _ => BadRequest(new { error = result.Error, code = result.ErrorCode })
            };
        }

        return Ok(result.Value);
    }

    [HttpDelete("{id:guid}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    public async Task<IActionResult> Delete(Guid id)
    {
        var result = await journalEntryService.DeleteJournalEntryAsync(id);
        if (!result.IsSuccess)
            return result.ErrorCode == "NOT_FOUND"
                ? NotFound(new { error = result.Error, code = result.ErrorCode })
                : BadRequest(new { error = result.Error, code = result.ErrorCode });

        return NoContent();
    }

    [HttpPost("{id:guid}/post")]
    [ProducesResponseType(typeof(JournalEntryDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    public async Task<IActionResult> Post(Guid id)
    {
        Guid userId = GetCurrentUserId();
        var result = await journalEntryService.PostJournalEntryAsync(id, userId);
        if (!result.IsSuccess)
        {
            return result.ErrorCode switch
            {
                "NOT_FOUND" => NotFound(new { error = result.Error, code = result.ErrorCode }),
                _ => BadRequest(new { error = result.Error, code = result.ErrorCode })
            };
        }

        return Ok(result.Value);
    }

    [HttpPost("{id:guid}/reverse")]
    [ProducesResponseType(typeof(JournalEntryDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status429TooManyRequests)]
    public async Task<IActionResult> Reverse(Guid id)
    {
        Guid userId = GetCurrentUserId();
        var result = await journalEntryService.ReverseJournalEntryAsync(id, userId);
        if (!result.IsSuccess)
        {
            return result.ErrorCode switch
            {
                "NOT_FOUND" => NotFound(new { error = result.Error, code = result.ErrorCode }),
                _ => BadRequest(new { error = result.Error, code = result.ErrorCode })
            };
        }

        return Ok(result.Value);
    }

    private Guid GetCurrentUserId()
    {
        string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? User.FindFirstValue("sub");
        return Guid.TryParse(userId, out Guid parsed) ? parsed : Guid.Empty;
    }
}

public record CreateJournalEntryRequest(
    DateOnly EntryDate,
    string Description,
    string? SourceModule = null,
    Guid? SourceDocumentId = null,
    string? SourceDocumentRef = null,
    bool IsAutoGenerated = false,
    List<CreateJournalEntryLineRequest>? Lines = null
);

public record CreateJournalEntryLineRequest(
    Guid GlAccountId,
    decimal DebitAmount,
    decimal CreditAmount,
    string? Description = null,
    Guid? ProjectId = null,
    Guid? CostCodeId = null
);

public record UpdateJournalEntryRequest(
    DateOnly? EntryDate = null,
    string? Description = null,
    List<CreateJournalEntryLineRequest>? Lines = null
);
