"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import api from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { TableSkeleton } from "@/components/skeletons";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { LoadingButton } from "@/components/ui/loading-button";
import { FileText, Check, RotateCcw } from "lucide-react";

const ALL_VALUE = "__all__";
const DEFAULT_PAGE_SIZE = 25;

type JournalEntryStatus = "Draft" | "Posted" | "Reversed";

interface JournalEntryDto {
  id: string;
  entryNumber: string;
  entryDate: string;
  description: string;
  status: JournalEntryStatus;
  sourceModule?: string | null;
  isAutoGenerated: boolean;
  totalDebits: number;
  totalCredits: number;
  postedAt?: string | null;
}

interface ListResult {
  items: JournalEntryDto[];
  totalCount: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

const statusColors: Record<JournalEntryStatus, "default" | "secondary" | "destructive"> = {
  Draft: "secondary",
  Posted: "default",
  Reversed: "destructive",
};

export default function JournalEntriesPage() {
  const router = useRouter();
  const [entries, setEntries] = useState<JournalEntryDto[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [totalCount, setTotalCount] = useState(0);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState(ALL_VALUE);
  const [postingId, setPostingId] = useState<string | null>(null);

  const fetchEntries = useCallback(async () => {
    setIsLoading(true);
    try {
      const params = new URLSearchParams();
      params.set("page", String(page));
      params.set("pageSize", String(DEFAULT_PAGE_SIZE));
      if (search.trim()) params.set("search", search.trim());
      if (statusFilter !== ALL_VALUE) params.set("status", statusFilter);

      const result = await api<ListResult>(`/api/journal-entries?${params.toString()}`);
      setEntries(result.items);
      setTotalCount(result.totalCount);
      setTotalPages(Math.max(result.totalPages || 1, 1));
    } catch {
      toast.error("Failed to load journal entries");
    } finally {
      setIsLoading(false);
    }
  }, [page, search, statusFilter]);

  useEffect(() => {
    fetchEntries();
  }, [fetchEntries]);

  useEffect(() => {
    setPage(1);
  }, [search, statusFilter]);

  async function handlePost(entry: JournalEntryDto) {
    if (!confirm(`Post journal entry ${entry.entryNumber}? This cannot be undone.`)) return;
    setPostingId(entry.id);
    try {
      await api(`/api/journal-entries/${entry.id}/post`, { method: "POST" });
      toast.success(`${entry.entryNumber} posted`);
      fetchEntries();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to post entry");
    } finally {
      setPostingId(null);
    }
  }

  async function handleReverse(entry: JournalEntryDto) {
    if (!confirm(`Reverse journal entry ${entry.entryNumber}? A new reversing entry will be created.`)) return;
    try {
      await api(`/api/journal-entries/${entry.id}/reverse`, { method: "POST" });
      toast.success(`${entry.entryNumber} reversed`);
      fetchEntries();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to reverse entry");
    }
  }

  async function handleDelete(entry: JournalEntryDto) {
    if (!confirm(`Delete draft entry ${entry.entryNumber}?`)) return;
    try {
      await api(`/api/journal-entries/${entry.id}`, { method: "DELETE" });
      toast.success("Entry deleted");
      fetchEntries();
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to delete entry");
    }
  }

  function formatCurrency(amount: number) {
    return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount);
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Journal Entries</h1>
          <p className="text-muted-foreground">General ledger journal entries and posting</p>
        </div>
        <Button
          className="bg-amber-500 hover:bg-amber-600 text-white"
          onClick={() => router.push("/accounting/journal-entries/new")}
        >
          <FileText className="h-4 w-4 mr-1" />
          New Entry
        </Button>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm font-medium">Filters</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-2">
              <Label>Search</Label>
              <Input
                placeholder="Entry number, description..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label>Status</Label>
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={ALL_VALUE}>All</SelectItem>
                  <SelectItem value="Draft">Draft</SelectItem>
                  <SelectItem value="Posted">Posted</SelectItem>
                  <SelectItem value="Reversed">Reversed</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      {isLoading ? (
        <TableSkeleton headers={["Entry #", "Date", "Description", "Debits", "Credits", "Status", "Actions"]} rows={8} />
      ) : totalCount === 0 ? (
        <EmptyState
          icon={FileText}
          title="No journal entries found"
          description="Create your first journal entry to get started."
          actionLabel="New Entry"
          actionHref="/accounting/journal-entries/new"
        />
      ) : (
        <Card>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Entry #</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead className="text-right">Debits</TableHead>
                  <TableHead className="text-right">Credits</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {entries.map((entry) => (
                  <TableRow key={entry.id}>
                    <TableCell className="font-medium">{entry.entryNumber}</TableCell>
                    <TableCell>{new Date(entry.entryDate + "T00:00:00").toLocaleDateString()}</TableCell>
                    <TableCell className="max-w-[300px] truncate">{entry.description}</TableCell>
                    <TableCell className="text-right font-mono">{formatCurrency(entry.totalDebits)}</TableCell>
                    <TableCell className="text-right font-mono">{formatCurrency(entry.totalCredits)}</TableCell>
                    <TableCell>
                      <Badge variant={statusColors[entry.status]}>{entry.status}</Badge>
                    </TableCell>
                    <TableCell className="text-right space-x-2">
                      {entry.status === "Draft" && (
                        <>
                          <LoadingButton
                            size="sm"
                            variant="outline"
                            loading={postingId === entry.id}
                            onClick={() => handlePost(entry)}
                          >
                            Post
                          </LoadingButton>
                          <Button size="sm" variant="destructive" onClick={() => handleDelete(entry)}>
                            Delete
                          </Button>
                        </>
                      )}
                      {entry.status === "Posted" && (
                        <Button size="sm" variant="outline" onClick={() => handleReverse(entry)}>
                          Reverse
                        </Button>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      )}

      <div className="flex items-center justify-between text-sm text-muted-foreground">
        <div>
          Showing {totalCount === 0 ? 0 : (page - 1) * DEFAULT_PAGE_SIZE + 1}-
          {Math.min(page * DEFAULT_PAGE_SIZE, totalCount)} of {totalCount}
        </div>
        <div className="flex items-center gap-2">
          <Button size="sm" variant="outline" disabled={page <= 1} onClick={() => setPage((p) => Math.max(1, p - 1))}>
            Previous
          </Button>
          <span>
            Page {page} / {totalPages}
          </span>
          <Button size="sm" variant="outline" disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}>
            Next
          </Button>
        </div>
      </div>
    </div>
  );
}
