using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using Pitbull.Billing.Features.JournalEntries;
using Pitbull.Billing.Features.VendorInvoices;
using Pitbull.Billing.Services;
using Pitbull.Core.CQRS;
using Pitbull.Core.Data;
using Pitbull.Core.Domain;
using Pitbull.Core.MultiTenancy;

namespace Pitbull.Tests.Unit.Billing;

public class VendorInvoiceServiceTests : IDisposable
{
    private static readonly Guid TestTenantId = Guid.NewGuid();
    private static readonly Guid TestCompanyId = Guid.NewGuid();
    private readonly PitbullDbContext _db;
    private readonly Mock<IJournalEntryService> _journalEntryServiceMock = new();
    private readonly VendorInvoiceService _service;

    public VendorInvoiceServiceTests()
    {
        TenantContext tenantContext = new() { TenantId = TestTenantId, TenantName = "Test" };
        CompanyContext companyContext = new() { CompanyId = TestCompanyId };

        DbContextOptions<PitbullDbContext> options = new DbContextOptionsBuilder<PitbullDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;

        _db = new PitbullDbContext(options, tenantContext, companyContext);
        _service = new VendorInvoiceService(
            _db,
            NullLogger<VendorInvoiceService>.Instance,
            _journalEntryServiceMock.Object);
    }

    public void Dispose()
    {
        _db.Dispose();
        GC.SuppressFinalize(this);
    }

    private CreateVendorInvoiceCommand ValidCreateCommand(decimal totalAmount = 5000m) =>
        new(VendorId: Guid.NewGuid(),
            InvoiceNumber: $"INV-{Guid.NewGuid().ToString()[..8]}",
            InvoiceDate: new DateOnly(2026, 2, 1),
            DueDate: new DateOnly(2026, 3, 1),
            TotalAmount: totalAmount,
            PurchaseOrderId: null);

    private async Task SeedGlAccountsAsync()
    {
        _db.Set<ChartOfAccount>().AddRange(
            new ChartOfAccount
            {
                Id = Guid.NewGuid(),
                TenantId = TestTenantId,
                CompanyId = TestCompanyId,
                AccountNumber = "5200",
                AccountName = "Subcontractor Expense",
                AccountType = AccountType.Expense,
                NormalBalance = NormalBalance.Debit,
                IsActive = true
            },
            new ChartOfAccount
            {
                Id = Guid.NewGuid(),
                TenantId = TestTenantId,
                CompanyId = TestCompanyId,
                AccountNumber = "2000",
                AccountName = "Accounts Payable",
                AccountType = AccountType.Liability,
                NormalBalance = NormalBalance.Credit,
                IsActive = true
            });
        await _db.SaveChangesAsync();
    }

    private void SetupJournalEntryMocks(Guid journalEntryId)
    {
        JournalEntryDto journalEntry = new(
            Id: journalEntryId,
            EntryNumber: "JE-0001",
            EntryDate: new DateOnly(2026, 2, 1),
            Description: "Vendor invoice accrual",
            Status: JournalEntryStatus.Draft,
            SourceModule: "VendorInvoice",
            SourceDocumentId: null,
            SourceDocumentRef: null,
            IsAutoGenerated: true,
            ReversalOfId: null,
            ReversedById: null,
            TotalDebits: 5000m,
            TotalCredits: 5000m,
            PostedByUserId: null,
            PostedAt: null,
            Lines: [],
            CreatedAt: DateTime.UtcNow,
            UpdatedAt: null);

        _journalEntryServiceMock
            .Setup(s => s.CreateJournalEntryAsync(It.IsAny<CreateJournalEntryCommand>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(Result.Success(journalEntry));

        _journalEntryServiceMock
            .Setup(s => s.PostJournalEntryAsync(journalEntryId, Guid.Empty, It.IsAny<CancellationToken>()))
            .ReturnsAsync(Result.Success(journalEntry with { Status = JournalEntryStatus.Posted }));
    }

    // ── HIGH #16: Non-positive total rejected ──

    [Fact]
    public async Task Create_ZeroAmount_ReturnsValidationError()
    {
        var result = await _service.CreateVendorInvoiceAsync(ValidCreateCommand(totalAmount: 0m));

        result.IsSuccess.Should().BeFalse();
        result.ErrorCode.Should().Be("VALIDATION_ERROR");
        result.Error.Should().Contain("positive");
    }

    [Fact]
    public async Task Create_NegativeAmount_ReturnsValidationError()
    {
        var result = await _service.CreateVendorInvoiceAsync(ValidCreateCommand(totalAmount: -100m));

        result.IsSuccess.Should().BeFalse();
        result.ErrorCode.Should().Be("VALIDATION_ERROR");
    }

    [Fact]
    public async Task Create_PositiveAmount_Succeeds()
    {
        var result = await _service.CreateVendorInvoiceAsync(ValidCreateCommand(totalAmount: 5000m));

        result.IsSuccess.Should().BeTrue();
        result.Value!.TotalAmount.Should().Be(5000m);
    }

    // ── HIGH #15: Status transition validation ──

    [Fact]
    public async Task Update_PendingToApproved_Succeeds()
    {
        var created = await _service.CreateVendorInvoiceAsync(ValidCreateCommand());
        created.IsSuccess.Should().BeTrue();

        var result = await _service.UpdateVendorInvoiceAsync(new UpdateVendorInvoiceCommand(
            VendorInvoiceId: created.Value!.Id,
            VendorId: null, InvoiceNumber: null, InvoiceDate: null, DueDate: null,
            TotalAmount: null, Status: VendorInvoiceStatus.Approved,
            PurchaseOrderId: null, ClearPurchaseOrderId: false));

        result.IsSuccess.Should().BeTrue();
        result.Value!.Status.Should().Be(VendorInvoiceStatus.Approved);
    }

    [Fact]
    public async Task Update_PendingToPaid_ReturnsInvalidTransition()
    {
        var created = await _service.CreateVendorInvoiceAsync(ValidCreateCommand());
        created.IsSuccess.Should().BeTrue();

        var result = await _service.UpdateVendorInvoiceAsync(new UpdateVendorInvoiceCommand(
            VendorInvoiceId: created.Value!.Id,
            VendorId: null, InvoiceNumber: null, InvoiceDate: null, DueDate: null,
            TotalAmount: null, Status: VendorInvoiceStatus.Paid,
            PurchaseOrderId: null, ClearPurchaseOrderId: false));

        result.IsSuccess.Should().BeFalse();
        result.ErrorCode.Should().Be("INVALID_STATUS_TRANSITION");
    }

    [Fact]
    public async Task Update_ApprovedToPending_ReturnsInvalidTransition()
    {
        var created = await _service.CreateVendorInvoiceAsync(ValidCreateCommand());
        created.IsSuccess.Should().BeTrue();

        await _service.UpdateVendorInvoiceAsync(new UpdateVendorInvoiceCommand(
            VendorInvoiceId: created.Value!.Id,
            VendorId: null, InvoiceNumber: null, InvoiceDate: null, DueDate: null,
            TotalAmount: null, Status: VendorInvoiceStatus.Approved,
            PurchaseOrderId: null, ClearPurchaseOrderId: false));

        var result = await _service.UpdateVendorInvoiceAsync(new UpdateVendorInvoiceCommand(
            VendorInvoiceId: created.Value!.Id,
            VendorId: null, InvoiceNumber: null, InvoiceDate: null, DueDate: null,
            TotalAmount: null, Status: VendorInvoiceStatus.Pending,
            PurchaseOrderId: null, ClearPurchaseOrderId: false));

        result.IsSuccess.Should().BeFalse();
        result.ErrorCode.Should().Be("INVALID_STATUS_TRANSITION");
    }

    [Fact]
    public async Task Update_PendingToApproved_PostsAccrualAndSetsJournalEntryId()
    {
        await SeedGlAccountsAsync();
        Guid journalEntryId = Guid.NewGuid();
        SetupJournalEntryMocks(journalEntryId);

        var created = await _service.CreateVendorInvoiceAsync(ValidCreateCommand(totalAmount: 4200m));
        created.IsSuccess.Should().BeTrue();

        var result = await _service.UpdateVendorInvoiceAsync(new UpdateVendorInvoiceCommand(
            VendorInvoiceId: created.Value!.Id,
            VendorId: null, InvoiceNumber: null, InvoiceDate: null, DueDate: null,
            TotalAmount: null, Status: VendorInvoiceStatus.Approved,
            PurchaseOrderId: null, ClearPurchaseOrderId: false));

        result.IsSuccess.Should().BeTrue();
        result.Value!.Status.Should().Be(VendorInvoiceStatus.Approved);

        _journalEntryServiceMock.Verify(
            s => s.CreateJournalEntryAsync(
                It.Is<CreateJournalEntryCommand>(c =>
                    c.SourceModule == "VendorInvoice"
                    && c.Lines!.Count == 2
                    && c.Lines[0].DebitAmount == 4200m
                    && c.Lines[1].CreditAmount == 4200m),
                It.IsAny<CancellationToken>()),
            Times.Once);
        _journalEntryServiceMock.Verify(
            s => s.PostJournalEntryAsync(journalEntryId, Guid.Empty, It.IsAny<CancellationToken>()),
            Times.Once);

        VendorInvoice? stored = await _db.Set<VendorInvoice>().FindAsync(created.Value!.Id);
        stored!.AccrualJournalEntryId.Should().Be(journalEntryId);
    }
}