namespace Pitbull.Api.Features.SeedData;

/// <summary>
/// Result of seed data operation
/// </summary>
public record SeedDataResult(
    int ProjectsCreated,
    int BidsCreated,
    int BidItemsCreated,
    int PhasesCreated,
    int CostCodesCreated,
    int EmployeesCreated,
    int ProjectAssignmentsCreated,
    int TimeEntriesCreated,
    int SubcontractsCreated = 0,
    int ChangeOrdersCreated = 0,
    int PaymentApplicationsCreated = 0,
    int CustomersCreated = 0,
    int VendorsCreated = 0,
    int VendorInvoicesCreated = 0,
    int OwnerContractsCreated = 0,
    int BillingApplicationsCreated = 0,
    int WipReportsCreated = 0,
    int RetentionHoldsCreated = 0,
    int PayPeriodsCreated = 0,
    int PayrollRunsCreated = 0,
    int SubmittalsCreated = 0,
    int PunchListItemsCreated = 0,
    int OwnerScheduleOfValuesCreated = 0,
    int SchedulesCreated = 0,
    int ScheduleActivitiesCreated = 0,
    int RfisCreated = 0,
    int DailyReportsCreated = 0,
    int ChartOfAccountsCreated = 0,
    int AccountingPeriodsCreated = 0,
    int JournalEntriesCreated = 0,
    int LienWaiversCreated = 0,
    int PurchaseOrdersCreated = 0,
    int NotificationsCreated = 0,
    int EquipmentCreated = 0,
    int BankAccountsCreated = 0,
    int WageDeterminationsCreated = 0,
    int ComplianceDocumentsCreated = 0,
    int TaxJurisdictionsCreated = 0,
    int MeetingsCreated = 0,
    int TasksCreated = 0,
    string Summary = ""
);
