namespace Pitbull.Core.Domain;

/// <summary>
/// General ledger journal entry header.
/// Every financial transaction flows through a journal entry.
/// </summary>
public class JournalEntry : BaseEntity, ICompanyScoped, ITenantScoped
{
    public Guid CompanyId { get; set; }

    /// <summary>Auto-generated sequential number (e.g., "JE-2026-000142").</summary>
    public string EntryNumber { get; set; } = string.Empty;

    /// <summary>Transaction date — determines the accounting period.</summary>
    public DateOnly EntryDate { get; set; }

    public string Description { get; set; } = string.Empty;

    public JournalEntryStatus Status { get; set; } = JournalEntryStatus.Draft;

    /// <summary>Which module generated this entry (null = manual).</summary>
    public string? SourceModule { get; set; }

    /// <summary>FK to the originating document.</summary>
    public Guid? SourceDocumentId { get; set; }

    /// <summary>Human-readable source reference (e.g., invoice number).</summary>
    public string? SourceDocumentRef { get; set; }

    public bool IsAutoGenerated { get; set; }

    /// <summary>FK to the entry this reverses (null if not a reversal).</summary>
    public Guid? ReversalOfId { get; set; }

    /// <summary>FK to the entry that reversed this one.</summary>
    public Guid? ReversedById { get; set; }

    /// <summary>Denormalized sum of all line debits.</summary>
    public decimal TotalDebits { get; set; }

    /// <summary>Denormalized sum of all line credits. Must equal TotalDebits.</summary>
    public decimal TotalCredits { get; set; }

    public Guid? PostedByUserId { get; set; }
    public DateTime? PostedAt { get; set; }

    // Navigation
    public List<JournalEntryLine> Lines { get; set; } = [];
}

public enum JournalEntryStatus
{
    Draft = 1,
    Posted = 2,
    Reversed = 3
}
